### ISSUE TITLE
Add Documentation

### ISSUE THREAD

**Issue by mineus64** [mineus64/WWU-Game-Jam-2022#5]
# Overview

As this is a public repo, we have access to a project wiki without needing to pay _money_. We will use this project wiki to hold documentation for the project.

# Objectives

- [x] Create a wiki for the repo
- [x] Add a custom sidebar for the wiki
- [x] Add a main page for the wiki
- [x] Write proper documentation

**Comment by Spaceguy5234** [comment]
Added an initial landing page for the wiki with a short summary, and the beginnings of a table of contents. In doing so, the wiki was also created. 😛

**Comment by mineus64** [comment]
The basic structure is complete and some sample documentation is present. Further documentation can be written as required. I'm closing this one for now.
